### ISSUE TITLE
Замечания к коду 10.04

### ISSUE THREAD

**Issue by mglukhikh** [AlexanderKuptsov/Cat_Grep#1]
- Функция `word` логически состоит из двух частей -- анализ командной строки и собственно фильтрация. Рекомендую разбить её на эти две части
- static mutable fields `newLines`, `checkV` -- стиль, которого в Java лучше избегать (за изменением таких полей очень непросто следить). Я бы советовал, пожалуй, создать объект вроде `CrepFilter` или `CrepChecker`, ответственный за решение задачи фильтрации, свойства `checkX` передавал бы ему в конструктор после анализа командной строки (и добавил бы геттеры для их чтения), а то, что он в итоге нашёл, возвращал бы как результат
- Игнорирование регистра слов -- в одном месте написано `if (checkI)`, в другом `if (!checkI)`. Похоже на баг. Кроме этого, такое условие в принципе надо проверять один раз, не дублируя его в двух разных ветках (что как раз и позволяет избежать подобных багов)
- Инвертирование условие фильтрации: я бы рассчитал вначале само условие -- результат `m.find()` или `line.contains` -- и после этого сравнил бы его с `checkV` на равенство, опять-таки избегая дублирования кода
- С исключениями сделано как-то нехорошо, я бы просто разрешил вашему методу кидать `IOException`. Его стоит обработать на верхнем уровне и написать пользователю, что произошло. Бросание базовых исключений вроде `Throwable`, `Exception`, `RuntimeException` в Java вообще не очень приветствуется, лучше использовать более конкретные типы исключений (вроде `IOException`, `IllegalStateException`, `IllegalArgumentException` и т.п.)
- `try..finally` можно заменить на `try with resources` (в лекциях я про них упоминал, если не помните, прочитайте, что это)
- в тестах стоит проверить все 8 комбинаций. Насколько я понимаю, как раз комбинация с багом оказалась пропущена

Я пока поставлю вам "4", может быть, коллеги захотят меня поправить. Оценку можно и нужно улучшить, делать тут вам осталось не так много

**Comment by gagarski** [comment]
По-моему, почти все замечания отсюда исправлены. Нет только обработки исключений на самом верхнем уровне.

/cc @mglukhikh

**Comment by mglukhikh** [comment]
Ну раз исправлены, я закрою тикет :) Оценка, вижу, уже улучшена до 4.75

**Comment by gagarski** [comment]
>  Нет только обработки исключений на самом верхнем уровне.

@AlexanderKuptsov, Исправлено, увидел.
